# Generated by Django 3.2 on 2021-09-25 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('travel', '여행'), ('develop', '자기 개발'), ('leisure', '여가'), ('healthy', '건강'), ('love', '사랑'), ('society', '사회'), ('dream', '꿈'), ('family', '가족'), ('more', '기타')], max_length=100)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
